# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debug_watch_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DebugWatchWidget(object):
    def setupUi(self, DebugWatchWidget):
        DebugWatchWidget.setObjectName("DebugWatchWidget")
        DebugWatchWidget.resize(290, 280)
        DebugWatchWidget.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(DebugWatchWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.positionLine = QtWidgets.QLineEdit(DebugWatchWidget)
        self.positionLine.setMinimumSize(QtCore.QSize(100, 0))
        self.positionLine.setObjectName("positionLine")
        self.gridLayout.addWidget(self.positionLine, 2, 1, 1, 1)
        self.itemTransOriginSetButton = QtWidgets.QPushButton(DebugWatchWidget)
        self.itemTransOriginSetButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.itemTransOriginSetButton.setObjectName("itemTransOriginSetButton")
        self.gridLayout.addWidget(self.itemTransOriginSetButton, 4, 2, 1, 1)
        self.objectNameLine = QtWidgets.QLineEdit(DebugWatchWidget)
        self.objectNameLine.setReadOnly(True)
        self.objectNameLine.setObjectName("objectNameLine")
        self.gridLayout.addWidget(self.objectNameLine, 1, 1, 1, 3)
        self.itemShapeCheck = QtWidgets.QCheckBox(DebugWatchWidget)
        self.itemShapeCheck.setMaximumSize(QtCore.QSize(150, 16777215))
        self.itemShapeCheck.setObjectName("itemShapeCheck")
        self.gridLayout.addWidget(self.itemShapeCheck, 5, 0, 1, 1)
        self.itemShapeColorButton = QtWidgets.QToolButton(DebugWatchWidget)
        self.itemShapeColorButton.setText("")
        self.itemShapeColorButton.setObjectName("itemShapeColorButton")
        self.gridLayout.addWidget(self.itemShapeColorButton, 5, 3, 1, 1)
        self.itemBoundingRectLine = QtWidgets.QLineEdit(DebugWatchWidget)
        self.itemBoundingRectLine.setMinimumSize(QtCore.QSize(100, 0))
        self.itemBoundingRectLine.setObjectName("itemBoundingRectLine")
        self.gridLayout.addWidget(self.itemBoundingRectLine, 3, 1, 1, 1)
        self.itemBoundingRectSetButton = QtWidgets.QPushButton(DebugWatchWidget)
        self.itemBoundingRectSetButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.itemBoundingRectSetButton.setObjectName("itemBoundingRectSetButton")
        self.gridLayout.addWidget(self.itemBoundingRectSetButton, 3, 2, 1, 1)
        self.itemBoundingRectCheck = QtWidgets.QCheckBox(DebugWatchWidget)
        self.itemBoundingRectCheck.setMinimumSize(QtCore.QSize(100, 0))
        self.itemBoundingRectCheck.setMaximumSize(QtCore.QSize(150, 16777215))
        self.itemBoundingRectCheck.setObjectName("itemBoundingRectCheck")
        self.gridLayout.addWidget(self.itemBoundingRectCheck, 3, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(DebugWatchWidget)
        self.groupBox_11.setMinimumSize(QtCore.QSize(0, 90))
        self.groupBox_11.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.checkBox_26 = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout_15.addWidget(self.checkBox_26, 3, 0, 1, 1)
        self.checkBox_25 = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout_15.addWidget(self.checkBox_25, 1, 0, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_15.addWidget(self.checkBox_24, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_11, 6, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(DebugWatchWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.itemTransOriginCheck = QtWidgets.QCheckBox(DebugWatchWidget)
        self.itemTransOriginCheck.setMaximumSize(QtCore.QSize(150, 16777215))
        self.itemTransOriginCheck.setObjectName("itemTransOriginCheck")
        self.gridLayout.addWidget(self.itemTransOriginCheck, 4, 0, 1, 1)
        self.pythonIDLine = QtWidgets.QLineEdit(DebugWatchWidget)
        self.pythonIDLine.setReadOnly(True)
        self.pythonIDLine.setObjectName("pythonIDLine")
        self.gridLayout.addWidget(self.pythonIDLine, 0, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(DebugWatchWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.positionSetButton = QtWidgets.QPushButton(DebugWatchWidget)
        self.positionSetButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.positionSetButton.setObjectName("positionSetButton")
        self.gridLayout.addWidget(self.positionSetButton, 2, 2, 1, 1)
        self.itemBoundingRectColorButton = QtWidgets.QToolButton(DebugWatchWidget)
        self.itemBoundingRectColorButton.setText("")
        self.itemBoundingRectColorButton.setObjectName("itemBoundingRectColorButton")
        self.gridLayout.addWidget(self.itemBoundingRectColorButton, 3, 3, 1, 1)
        self.itemTransOriginLine = QtWidgets.QLineEdit(DebugWatchWidget)
        self.itemTransOriginLine.setMinimumSize(QtCore.QSize(100, 0))
        self.itemTransOriginLine.setObjectName("itemTransOriginLine")
        self.gridLayout.addWidget(self.itemTransOriginLine, 4, 1, 1, 1)
        self.positionColorButton = QtWidgets.QToolButton(DebugWatchWidget)
        self.positionColorButton.setText("")
        self.positionColorButton.setObjectName("positionColorButton")
        self.gridLayout.addWidget(self.positionColorButton, 2, 3, 1, 1)
        self.positionCheck = QtWidgets.QCheckBox(DebugWatchWidget)
        self.positionCheck.setMaximumSize(QtCore.QSize(150, 16777215))
        self.positionCheck.setObjectName("positionCheck")
        self.gridLayout.addWidget(self.positionCheck, 2, 0, 1, 1)
        self.itemTransOriginColorButton = QtWidgets.QToolButton(DebugWatchWidget)
        self.itemTransOriginColorButton.setText("")
        self.itemTransOriginColorButton.setObjectName("itemTransOriginColorButton")
        self.gridLayout.addWidget(self.itemTransOriginColorButton, 4, 3, 1, 1)

        self.retranslateUi(DebugWatchWidget)
        QtCore.QMetaObject.connectSlotsByName(DebugWatchWidget)

    def retranslateUi(self, DebugWatchWidget):
        _translate = QtCore.QCoreApplication.translate
        DebugWatchWidget.setWindowTitle(_translate("DebugWatchWidget", "Form"))
        self.itemTransOriginSetButton.setText(_translate("DebugWatchWidget", "set"))
        self.itemShapeCheck.setText(_translate("DebugWatchWidget", "shape"))
        self.itemBoundingRectSetButton.setText(_translate("DebugWatchWidget", "set"))
        self.itemBoundingRectCheck.setText(_translate("DebugWatchWidget", "bounding rect"))
        self.groupBox_11.setTitle(_translate("DebugWatchWidget", "Parent\'s boolean options"))
        self.checkBox_26.setText(_translate("DebugWatchWidget", "accept touch events"))
        self.checkBox_25.setText(_translate("DebugWatchWidget", "filters child events"))
        self.checkBox_24.setText(_translate("DebugWatchWidget", "accepts hover events"))
        self.label_4.setText(_translate("DebugWatchWidget", "PyQt item.objectName( )"))
        self.itemTransOriginCheck.setText(_translate("DebugWatchWidget", "transform. origin"))
        self.label_3.setText(_translate("DebugWatchWidget", "Python id(item)"))
        self.positionSetButton.setText(_translate("DebugWatchWidget", "set"))
        self.positionCheck.setText(_translate("DebugWatchWidget", "position"))

